name: Create Tag, Release and Publish package to NuGet

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version from .csproj
        id: extract-version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/Nhtsa.SDK.Clients/Nhtsa.SDK.Clients.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Tag and push it
        run: |
          TAG="v${{ env.VERSION }}"

          git tag -a "$TAG" -m "Stable $TAG"
          git push origin "$TAG"
